main/urls.py
from django.urls import path
from main.api import api_views, shop_view
from main import views

urlpatterns = [
    path('getting-started/',views.BaseView.as_view(),name='home' ),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('mytimeslots/', views.MytimeslotsView.as_view(), name='mytimeslots'),
    path('notifications/', views.NotificationView.as_view(), name='notifications'),
    path('shops-near-me/', views.shop_near_me, name='explore'),
    path('shops-slots/<str:gst_id>/', views.shop_slots, name='shop-slots'),
    path('api/shop-list/<int:pin>/', api_views.ShopView.as_view(), name='shops'),
    path('api/shop-slots/<str:gst_id>/', api_views.list_slots_for_shop, name='slots'),
    path('api/shops-by-category-and-city/', api_views.get_shop_by_category_and_city, name='shops-by-category-and-city'),
    path('api/shops-by-city/', api_views.get_shop_by_city, name='shops-by-city'),
    path('shop-by-category/<int:cat>/', views.shop_by_cat, name='shop-by-cat'),
    path('api/search-shop/<str:query>/',api_views.search_for_shop, name='search'),
    path('create-buy-in/<str:slot_id>',views.create_buy_in_booking, name='buy-in'),
    path('create-pickup-in/<str:slot_id>',views.create_pick_up_booking, name='pick-up'),
    path('api/pickup-notification/', api_views.create_notification, name= 'pick-up-notification'),
    path('api/get-shop-details/<str:gst_id>/', api_views.get_shop_details, name='get-shop-details'),
    path('api/change-shop-start-time/<str:gst_id>/', api_views.change_shop_start_time, name= 'change-shop-start-time'),
    path('api/change-shop-stop-time/<str:gst_id>/', api_views.change_shop_stop_time, name= 'change-shop-stop-time'),
    path('api/add-break-day/<str:gst_id>/', api_views.add_day_break, name= 'add-daybreak'),
    path('is-next-day-off/<str:gst_id>/', api_views.is_next_day_off, name='is-next-day-off'),
    path('api/add-break/<str:gst_id>/', api_views.create_break, name='create-break'),
    path('pick-up-form/<str:slot_id>/', views.pick_up_view, name='pick-up-form'),
    path('mytimeslots-post-confirmation/<str:slot_id>/', views.my_timeslots_post_confirmation, name='my-timeslots-post-confirmation'),
    path('api/edit-payment-remark/', shop_view.shop_detail, name='payment-remark-details')
]

socors_backend/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include('allauth.urls')),
    path('', RegisterView.as_view(), name='register')
]

user/urls.py
from django.urls import path
from user.api import auth
from django.contrib.auth.views import LogoutView, LoginView
from .views import login_view, edit_address, remove_address, change_main_address, update_profile, add_address, AddaddressView, ProfileView, RegisterView,AddAddressView, AfterAddressView, TermsConditionsView, PrivacyPolicyView
from .api.auth import ValidatePhoneSendOTP, validateOTP
from .api.api_views import profile_details

urlpatterns = [
    path('api/login/', auth.LoginView.as_view(), name='api-login'),
    # path('login/', LoginView.as_view(
    #     template_name='login.html'
    # ), name='login'),
    path('login/', login_view, name="login"),
    path('api/new-address/',add_address, name='add-address/'),
    path('api/validate-phone/',  ValidatePhoneSendOTP.as_view(), name='validate-phone-number'),
    path('api/otp/', validateOTP.as_view(), name='validate-otp'),
    path('api/add-address/', AddaddressView.as_view(), name='api-add-address'),
    path('after-address-profile/', AfterAddressView.as_view(), name='after-address'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', RegisterView.as_view(), name='register'),
    path('api/user-details/', profile_details, name='user-details'),
    path('logout/', LogoutView.as_view(
        next_page='/'
    ),name='logout'),
    path('add-address/', AddAddressView, name='add-address'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms-and-conditions/', TermsConditionsView.as_view(), name='terms-n-conditions'),
    path('update-profile/', update_profile, name='update-profile'),
    path('change-main-address/', change_main_address, name='change-main-address'),
    path('remove-address/', remove_address, name='remove-address'),
    path('edit-address/', edit_address, name='edit-address')
]

main/forms.py
from django import forms
from user.models import User, Address
from .models import PickUpBooking

class PickUpForm(forms.ModelForm):
    class Meta(object):
        model = PickUpBooking
        fields = ['message_for_shopkeeper']

main/views.py
from user.models import User
from main.models import Shop,Slot,BuyInBooking, PickUpBooking, PickUpNotification
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from .forms import PickUpForm
from main.shopkeeper_helpers import send_pick_up_to_shopkeeper, send_buy_in_to_shopkeeper
from datetime import datetime, timedelta
# ------------------------------------------------------------------------------
# -----------------GENERIC VIEWS FOR TEMPLATES----------------------------------
# ------------------------------------------------------------------------------

class BaseView(TemplateView):
    login_url = '/user/login/'
    template_name = 'home.html'

class MenuView(LoginRequiredMixin,TemplateView):
    model=User, Shop, Slot
    login_url = '/user/login/'
    template_name = 'menu.html'

class NotificationView(LoginRequiredMixin,TemplateView):
    model = User, Shop, Slot, PickUpNotification
    login_url = '/user/login/'
    template_name = 'notifications.html'

class MytimeslotsView(LoginRequiredMixin,TemplateView):
    model = User, Shop, Slot, BuyInBooking,PickUpBooking
    login_url = '/user/login/'
    template_name = 'mytimeslots.html'

class MytimeslotsView(LoginRequiredMixin,TemplateView):
    model = User, Shop, Slot, BuyInBooking,PickUpBooking
    login_url = '/user/login/'
    template_name = 'mytimeslots.html'



# ----------------------------------------------------------------
# -----------------ACTION VIEWS-----------------------------------
# ----------------------------------------------------------------

def pick_up_view(request, slot_id):
    if request.method == 'POST':
        data = request.POST.dict()
        items_dict      = {k:v for (k,v) in data.items() if k.startswith('item')}
        quantity_dict   = {k:v for (k,v) in data.items() if k.startswith('qty')}
        remark_dict     = {k:v for (k,v) in data.items() if k.startswith('remark')}
        order = 'Order is\n'
        for key,item in items_dict.items():
            key_number = key[4:]
            quatity_name = 'qty'+str(key_number)
            remark_name  = 'remark'+str(key_number)
            if quatity_name in quantity_dict:
                quantity = quantity_dict[quatity_name]
            else:
                quantity = 'N/A'
            if  remark_name in remark_dict:
                remark = remark_dict[remark_name]
            else:
                remark = 'N/A'
            order = order + 'Item:' + str(item) + ' Quantity:' + str(quantity) + ' Remark:' + str(remark) + '\n'
        # print(order)
        if request.POST['Delivery']=='1':
            is_delivery = True
        else:
            is_delivery = False
        slot = Slot.objects.get(slot_id=slot_id)
        pickup = PickUpBooking()
        pickup.user = request.user
        pickup.slot = slot
        pickup.shop = slot.shop
        pickup.message_for_shopkeeper = order
        pickup.is_delivery = is_delivery
        pickup.save()
        send_pick_up_to_shopkeeper(is_delivery,str(slot.slot_id), str(pickup.pick_up_id), str(pickup.user.id), str(pickup.user.full_name), str(pickup.message_for_shopkeeper))

        url = reverse('main:my-timeslots-post-confirmation', kwargs={'slot_id': slot.slot_id})
        return HttpResponseRedirect(url)
    else:
        print("1")
        try:
            slot = Slot.objects.get(slot_id=slot_id)
            if (request.GET.get('delivery') == 'True'):
                return render(request, 'pickupform.html', {
                    'is_delivery': True,
                    "slot_id": slot.slot_id
                })
            else:
                return render(request, 'pickupform.html', {"slot_id": slot.slot_id})
        except:
            slot = Slot.objects.get(slot_id=slot_id)
            return render(request, 'pickupform.html', {"slot_id": slot.slot_id})



def shop_near_me(request):
    user=request.user
    pin = 0
    for address in user.address.all():
        if address.is_main:
            pin=address.pincode
    shops=Shop.objects.filter(shop_pincode__exact=int(pin))
    return render(request, 'shopsnearme.html', {'shops':shops})

def shop_slots(request,gst_id):
    shop=Shop.objects.get(gst_id=gst_id)
    if shop.stop_time < datetime.today().time():
        tomorrow = datetime.today()+timedelta(days=1)
        slots = Slot.objects.filter(
            shop= shop,
            slot_start_time__day= tomorrow.day,
            slot_stop_time__month= tomorrow.month,
        )
        return render(request, 'shopslots.html', {'slots': slots, 'shop': shop, 'date': tomorrow.date()})
    else:
        slots=Slot.objects.filter(
            shop=shop,
            slot_start_time__day = datetime.today().day,
            slot_start_time__month = datetime.today().month,
            is_break=False)
        return render(request, 'shopslots.html', {'slots':slots, 'shop': shop, 'date': datetime.today().date()})

def shop_by_cat(request, cat):
    user=request.user
    try:
        address=user.address.get(is_main=True)
    except:
        return HttpResponseRedirect('/user/add-address/')
    city=address.city
    shops=Shop.objects.filter(shop_city=city, shop_type=cat)
    return render(request, 'shopsnearme.html', {'shops':shops})

def create_buy_in_booking(request, slot_id):
    if request.method== "POST":
        slot = Slot.objects.get(slot_id=slot_id)
        user = request.user
        shop = slot.shop
        slot.num_entries_left=slot.num_entries_left-1
        slot.save()
        try:
            buyin = BuyInBooking.objects.get(slot=slot, user=user)
            return HttpResponseRedirect('/mytimeslots/')
        except:
            buyin=BuyInBooking()
            buyin.user=user
            buyin.slot=slot
            buyin.shop=shop
            buyin.save()
            print(buyin.buy_in_id)
            send_buy_in_to_shopkeeper(str(slot.slot_id), str(buyin.buy_in_id), str(user.id), str(user.full_name))
            url = reverse('main:my-timeslots-post-confirmation', kwargs={'slot_id': slot.slot_id})
            return HttpResponseRedirect(url)

def create_pick_up_booking(request, slot_id):
    if request.method == "POST":
        print(request.POST)
        form = PickUpForm(request.POST)
        if form.is_valid():
            pickup      = form.save(commit=False)
            pickup.user = request.user
            slot        = Slot.objects.get(slot_id=slot_id)
            pickup.slot = slot
            pickup.shop = slot.shop
            pickup.save()
            send_pick_up_to_shopkeeper(str(slot.slot_id), str(pickup.pick_up_id), str(pickup.user.id), str(pickup.user.full_name), str(pickup.message_for_shopkeeper))
            return HttpResponseRedirect('/mytimeslots')
    else:
        form = PickUpForm()
    # Check whether delivery is true
    '''
    print("1")
    try:
        print("Idhar to pahuncha")
        if(request.GET.get('delivery') == 'True'):
            return render(request, 'shopslots.html', {
                'is_delivery': True,
                'form': form
            })
    except:
    '''
    return render(request, 'shopslots.html', {
        'form': form
    })


def my_timeslots_post_confirmation(request,slot_id):
    fin_slot = Slot.objects.get(slot_id=slot_id)
    return render(request, 'mytimeslotswithconfirmation.html', {
        "fin_slot":fin_slot
    })

main/templates/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha256-L/W5Wfqfa0sdBNIKN9cG6QA5F2qx4qICmU2VgLruv9Y="
      crossorigin="anonymous"
    />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;800&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">


    <title>Menu</title>
</head>
<body>
    <script>
      baseURL='https://socorsnearyou.xyz/';
    </script>
    <nav class="navbar navbar-expand-xxl navbar-dark bg justify-content-xxl-start fixed-top">
        <a class="navbar-brand order-0 ml-xxl-0 ml-2 mr-auto" href="{% url 'main:menu' %}">SOCORS</a>
        <a id="explore_page" class="mr-3" href="{% url 'main:explore' %}"><span class="fas fa-home" id="home"></span></a>
        <a id="notification" href="{% url 'main:notifications' %}"><span class="fas fa-bell" id="bell"></span>
          <!-- <span class="badge badge-danger rounded-circle" id="bell_num">5</span> -->
          <!-- if no notification -->
          <!-- <span class="badge badge-danger rounded-circle invisible">5</span> -->
        </a>      
        
        <button id="tri" class="navbar-toggler align-self-start" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex flex-column flex-xxl-row bg mobileMenu" id="navbarSupportedContent">
          
          <div class="picture">
            <img src="{% static 'images/user_dp.png' %}" alt="profile_picture" class="dp">
            <p id="nav_name" class="mb-0">{{ user.full_name }}<a href="{% url 'user:update-profile' %}"><img id="edit_name" src="{% static 'images/edit_icon.png' %}" alt=""></a></p></p>
          </div>

          <div class="list">
            <ul class="navbar-nav align-self-stretch" id="menu">
              <li class="nav-item">
                <a class="link" href="{% url 'user:profile' %}">My Profile</a>
              </li>
			  <li class="nav-item">
                <a class="link" href="{% url 'main:explore' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'main:menu' %}">Explore</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'main:mytimeslots' %}" tabindex="-1" aria-disabled="true">My Timeslots</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'user:add-address' %}" tabindex="-1" aria-disabled="true">Add Address</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'main:notifications' %}" tabindex="-1" aria-disabled="true">Notifications</a>
              </li>
              <li class="nav-item">
                <a class="link" tabindex="-1" href="#" aria-disabled="true" data-toggle="modal" data-target="#ContactUsModal">Contact Us</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'user:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
      <!--Contact Us Modal-->

		<div id="ContactUsModal" class="modal fade" role="dialog">
			<div class="modal-dialog-centered modal-dialog" role="content">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header justify-content-center pt-1 pb-0 bg-primary">
            <h4 class="row text-white">Contact Us at</h4>	
					</div>
					<div class="modal-body pt-2">
            <div class="row">
              <p class="text-center w-100 mb-2">For feedback and suggestions</p>
            </div>
            <div class="align-items-center mb-1 ml-5 row">
              <i class="fa-whatsapp-square fab text-success" style="font-size: 30px;" aria-hidden="true"></i>
              <span class="pl-2" style="font-size: 15px;">+91-7042676330</span>
            </div>
            <div class="align-items-center ml-5 row">
              <a href = "mailto: socorsnearyou@gmail.com" class="text-danger">
                <i class="fas fa-envelope" style="font-size: 30px;" aria-hidden="true"></i>
              </a>
              <span class="pl-2 mb-1" style="font-size: 15px;">socorsnearyou@gmail.com</span>                
            </div>
        </div>
				</div>
			</div>
		</div>
    <div class="overlay"></div>

    <div class="content">
            <input id="search_input" class="inputmargin" type="search" placeholder="Enter shop name, product name or product type">
            
            <div class="row">
                <div class="line left">
                    <div class="top">
                        <a href="{% url 'main:shop-by-cat' cat=1 %}"> <img class="ico groc" src="{% static 'images/grocs.png' %}" alt=""></a>
                    </div>
                    <div class="bottom">
                        Groceries
                    </div>
                </div>
                <div class="line right">
                    <div class="top">
                        <a href="{% url 'main:shop-by-cat' cat=2 %}"><img class="ico" src="{% static 'images/veggies.png' %}" alt=""></a>
                    </div>
                    <div class="bottom">
                        Fruits and Vegetables
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="line left">
                    <div class="top">
                        <a href="{% url 'main:shop-by-cat' cat=3 %}"><img class="ico" src="{% static 'images/cake.png' %}" alt=""></a>
                    </div>
                    <div class="bottom">
                        Bakery
                    </div>
                </div>
                <div class="line right">
                    <div class="top">
                        <a href="{% url 'main:shop-by-cat' cat=4 %}"><img class="ico" src="{% static 'images/elec.png' %}" alt=""></a>
                    </div>
                    <div class="bottom">
                        Electronics and Electrical
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="line left">
                    <div class="top">
                        <a href="{% url 'main:shop-by-cat' cat=5 %}"><img class="ico" src="{% static 'images/pharm.png' %}" alt=""></a>
                    </div>
                    <div class="bottom">
                        Pharmacy
                    </div>
                </div>
                <div class="line right">
                    <div class="top">
                        <a href="{% url 'main:shop-by-cat' cat=6 %}"><img class="ico" src="{% static 'images/clothes.png' %}" alt=""></a>
                    </div>
                    <div class="bottom">
                        Clothing and Apparels
                    </div>
                </div>
    </div>
</div>


    <script
			  src="https://code.jquery.com/jquery-3.5.1.min.js"
			  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
              crossorigin="anonymous"></script>
              
              <script
              src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"
              integrity="sha256-OUFW7hFO0/r5aEGTQOz9F/aXQOt+TwqI1Z4fbVvww04="
              crossorigin="anonymous"
            ></script>
    <script src="{% static 'js/menu.js' %}"></script>
</body>
</html>

main/templates/shopsnearme.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/shopsnearme.css' %}">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha256-L/W5Wfqfa0sdBNIKN9cG6QA5F2qx4qICmU2VgLruv9Y="
      crossorigin="anonymous"
    />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">

    <title>Shops near me</title>
</head>
<body>
    <nav class="navbar navbar-expand-xxl navbar-dark bg justify-content-xxl-start fixed-top">
        <a class="navbar-brand order-0 ml-xxl-0 ml-2 mr-auto" href="{% url 'main:menu' %}">SOCORS</a>
        <a id="explore_page" class="mr-3" href="{% url 'main:explore' %}"><span class="fas fa-home" id="home"></span></a>
        <a id="notifications" class="mr-1" href="{% url 'main:notifications' %}"><span class="fas fa-bell" id="bell"></span>
          <!-- <span class="badge badge-danger rounded-circle" id="bell_num">5</span> -->
          <!-- if no notification -->
          <!-- <span class="badge badge-danger rounded-circle invisible">5</span> -->
        </a>
        <button id="tri" class="navbar-toggler align-self-start" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex flex-column flex-xxl-row bg mobileMenu" id="navbarSupportedContent">
          
          <div class="picture">
            <img src="{% static 'images/user_dp.png' %}" alt="profile_picture" class="dp">
            <p id="nav_name" class="mb-0">{{ user.full_name }}<a href="{% url 'user:update-profile' %}"> <img id="edit_name" src="{% static 'images/edit_icon.png' %}" alt=""></a></p>
          </div>

          <div class="list">
            <ul class="navbar-nav align-self-stretch" id="menu">
              <li class="nav-item">
                <a class="link" href="{% url 'user:profile' %}">My Profile</a>
              </li>
			  <li class="nav-item">
                <a class="link" href="{% url 'main:explore' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'main:menu' %}">Explore</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'main:mytimeslots' %}" tabindex="-1" aria-disabled="true">My Timeslots</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'user:add-address' %}" tabindex="-1" aria-disabled="true">Add Address</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'main:notifications' %}" tabindex="-1" aria-disabled="true">Notifications</a>
              </li>
              <li class="nav-item">
                <a class="link" tabindex="-1" aria-disabled="true" href="#" data-toggle="modal" data-target="#ContactUsModal">Contact Us</a>
              </li>
              <li class="nav-item">
                <a class="link" href="{% url 'user:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!--Contact Us Modal-->

		<div id="ContactUsModal" class="modal fade" role="dialog">
			<div class="modal-dialog-centered modal-dialog" role="content">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header justify-content-center pt-1 pb-0 bg-primary">
						<h4 class="row text-white">Contact Us at</h4>	
					</div>
					<div class="modal-body pt-2">
            <div class="row">
              <p class="text-center w-100 mb-2">For feedback and suggestions</p>
            </div>
            <div class="align-items-center mb-1 ml-5 row">
              <i class="fa-whatsapp-square fab text-success" style="font-size: 30px;" aria-hidden="true"></i>
              <span class="pl-2" style="font-size: 15px;">+91-7042676330</span>
            </div>
            <div class="align-items-center ml-5 row">
              <a href = "mailto: socorsnearyou@gmail.com" class="text-danger">
                <i class="fas fa-envelope" style="font-size: 30px;" aria-hidden="true"></i>
              </a>
              <span class="pl-2 mb-1" style="font-size: 15px;">socorsnearyou@gmail.com</span>                
            </div>
        </div>
				</div>
			</div>
		</div>
    <div class="overlay"></div>
    
    <div class="content">
        
        <h1 id="h1" class="d-flex align-self-start h1margin mb-0">Shops near me</h1>
        <div class="alert alert-info pt-1 pb-1" style="font-size: 12px;" id="change_add">
            {% for a in user.address.all %}
                {% if a.is_main %}
                    <span><strong>Currently at {{ a.area }}, {{ a.city }}.</strong></span>
                {% endif %}
            {% endfor %}
            <br>
            <a href="{% url 'user:profile' %}"> Change Address here.</a>
        </div>
        
        {% if user.address.all.exists %}
        {% for shop in shops %}
            <div class="shop row">

            <div class="col-3">
                <div class="row"><img src="{% static 'images/shop.png' %}" alt="shop_img">
                </div>
        {% if shop.is_shop_open %}
          <div class="shop_status" >Status: <span style="color: green;">Open</span></div>
        {% else %}
          <div class="shop_status" >Status: <span style="color: red;">Closed</span></div>
        {% endif %}  
            </div>

            <div class="col-7">
                <div class="row justify-content-center">
                   <p class="shop_name">{{ shop.shop_name }}</p>
                </div>
                <div class="row">
                        <p class="shop_address">{{ shop.shop_area }}, {{ shop.shop_city }}</p>
                </div>
                <div class="d-flex flex-row-reverse">
                    <form action="{% url 'main:shop-slots' gst_id=shop.gst_id %}">
                        <input type="submit" class="btn btn-info btn-overide" value="Get Timeslot">
                    </form>
                </div>

            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="alert alert-danger pt-1 pb-1" style="font-size: 12px;">
          <span><strong>Please add an address. </strong></span>
          <a href="{% url 'user:add-address' %}">Click here.</a>
          <script>
            document.getElementById('change_add').style.display="none"
          </script>
        </div>        {% endif %}
    </div>
    <script
			  src="https://code.jquery.com/jquery-3.5.1.min.js"
			  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
              crossorigin="anonymous"></script>
              
              <script
              src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"
              integrity="sha256-OUFW7hFO0/r5aEGTQOz9F/aXQOt+TwqI1Z4fbVvww04="
              crossorigin="anonymous"
            ></script>
    <script src="{% static 'js/shopsnearme.js' %}"></script>
</body>
</html>